config/routes.rb
Rails.application.routes.draw do

  get 'todo_lists/:id/todo_items' => 'todo_items#index', as: :view

  post 'todo_lists/:todo_list_id/todo_items' => 'todo_items#index', as: :move_up

  root 'todo_lists#index'

  resources :todo_items

  resources :todo_lists

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base

  belongs_to :todo_list, :polymorphic =>true
  acts_as_list scope: :todo_list

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  helper_method :move_up
  # GET /todo_items
  # GET /todo_items.json
  def index

      @todo_items = TodoItem.where(:todo_list_id => params[:id]).order(position: :asc)
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  #POST /todo_item
  def move_up
    @todo_item=ToDoItem.find(params[:id])

@todo_item.save
  end


  def move_down

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:itemName, :position, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :Description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoplist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for @todo_item, :html => { :class => "form-horizontal todo_item" } do |f| %>

    <% if @todo_item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @todo_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :itemName, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :itemName, :class => 'form-control' %>
    </div>
    <%= error_span(@todo_item[:itemName]) %>
  </div>


    <div class="control-group">
      <%= f.label :position, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :position, :class => 'form-control' %>
      </div>
      <%= error_span(@todo_item[:itemName]) %>
    </div>



    <div class="control-group">
      <%= f.label :list_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :todo_list_id, :class => 'form-control' %>
      </div>
      <%= error_span(@todo_item[:itemName]) %>
    </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            todo_items_path, :class => 'btn btn-default' %>

<% end %>

app/views/todo_items/edit.html.erb
<%- model_class = TodoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_items/index.html.erb
<%- model_class = TodoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:itemName) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:todo_list_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>

    <% @todo_items.each do |todo_item|  %>
      <tr>
        <td><%= link_to todo_item.id, todo_item_path(todo_item) %></td>
        <td><%= todo_item.itemName %></td>
        <td><%= todo_item.position %></td>
        <td><%= todo_item.todo_list_id %></td>
        <td><%=l todo_item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_todo_item_path(todo_item), :class => 'btn btn-default btn-xs' %>



          <%= link_to t('.index', :default => t("move up")),
                       move_up_url(:position), method: :move_up, :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.move_down', :default => t("move_down")),
                      todo_item_path(todo_item), :class => 'btn btn-default btn-xs' %>


          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      todo_item_path(todo_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_todo_item_path,
            :class => 'btn btn-primary' %>

app/views/todo_items/move_up.erb
<%- model_class = TodoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_items/new.html.erb
<%- model_class = TodoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_items/show.html.erb
<%- model_class = TodoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:itemName) %>:</strong></dt>
  <dd><%= @todo_item.itemName %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              todo_items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_todo_item_path(@todo_item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              todo_item_path(@todo_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list, :html => { :class => "form-horizontal todo_list" } do |f| %>

    <% if @todo_list.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @todo_list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@todo_list[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :Description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Description, :class => 'form-control' %>
    </div>
    <%= error_span(@todo_list[:Description]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            todo_lists_path, :class => 'btn btn-default' %>

<% end %>

app/views/todo_lists/edit.html.erb
<%- model_class = TodoList -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_lists/index.html.erb
<%- model_class = TodoList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:Description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= link_to todo_list.id, todo_list_path(todo_list) %></td>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.Description %></td>
        <td><%=l todo_list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_todo_list_path(todo_list), :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.index', :default => t("view")),
                     view_url(todo_list.id), :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      todo_list_path(todo_list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_todo_list_path,
            :class => 'btn btn-primary' %>

app/views/todo_lists/new.html.erb
<%- model_class = TodoList -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_lists/show.html.erb
<%- model_class = TodoList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @todo_list.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Description) %>:</strong></dt>
  <dd><%= @todo_list.Description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              todo_lists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_todo_list_path(@todo_list), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              todo_list_path(@todo_list),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>